### POST Membuat Pesanan Baru
# Ganti user ID dengan ID user yang sudah ada di MongoDB
# Ganti product ID dengan _id produk yang sudah ada di MongoDB (lihat collection products)
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "user": "68f5ed0fda8f9a72ff023aba", 
    "orderItems": [
        {
            "product": "68f5f6561b6ace6a455e83b1", 
            "quantity": 2
        },
        {
            "product": "68f5f66b1b6ace6a455e83b3",
            "quantity": 1
        }
    ]
}

### GET Semua Pesanan
GET http://localhost:3000/api/orders

### GET Detail Pesanan (Ganti ID)
GET http://localhost:3000/api/orders/68f5f6a4c98e95671fc07068

### PUT Update Status Pesanan (Ganti ID)
PUT http://localhost:3000/api/orders/68f5f6a4c98e95671fc07068
Content-Type: application/json

{
    "status": "Shipped"
}