### POST Membuat Pesanan Baru
# Ganti user ID dengan ID user yang sudah ada di MongoDB
# Ganti product ID dengan _id produk yang sudah ada di MongoDB (lihat collection products)
POST http://localhost:3000/api/orders
Content-Type: application/json

{
    "user": "68f2376c11296c1c84db3393", 
    "orderItems": [
        {
            "product": "68f5e82e7a818c26b391241f", 
            "quantity": 2
        },
        {
            "product": "68f5e84a7a818c26b3912421",
            "quantity": 1
        }
    ]
}

### GET Semua Pesanan
GET http://localhost:3000/api/orders

### GET Detail Pesanan (Ganti ID)
GET http://localhost:3000/api/orders/68f2483781f31b290702dad5

### PUT Update Status Pesanan (Ganti ID)
PUT http://localhost:3000/api/orders/68f2483781f31b290702dad5
Content-Type: application/json

{
    "status": "Shipped"
}